### ISSUE TITLE
Can't perform Project Member Actions despite being Project Member

### ISSUE THREAD

**Issue by MaxKissgen** [rwth-acis/RequirementsBazaar#166]
While handling the WebOCD project on chair i5's running instance of ReqBazaar, we noticed that none of our actions to act as requirement developer or to mark a requirement as done were successful. 

On performing those actions we get the errors:
`Only project members can register to develop a requirement.`
`Only project members can set requirements as realized.` 
We are however listed as project managers/developers in the project so in theory this should work.

**Comment by MaxKissgen** [comment]
The usernames I can confirm to not work at this point are are MaxKissgen, bekazhvania

**Comment by fxjordan** [comment]
I reproduced and fixed the problem with 'developing a requirement' (not yet deployed)

However, I cannot reproduce the error when setting a requirement as realized. Can send me a specific requirement ID in the project and the user for which this operation is not working.
(If I had to guess, I'd say the second error is only happening with the 'bekazhvania' user and not 'MaxKissgen'. Can you confirm?)

**Comment by MaxKissgen** [comment]
Alright, thank you very much for the quick resolution!

Your guess seems to be right. I just tried it out setting a requirement as realized works as MaxKissgen, **the problem for 'bekazhvania' still remains**.
The id of the requirement is **2804**
with the corresponding link https://requirements-bazaar.org/projects/137/requirements/2804

**Comment by fxjordan** [comment]
The problem here is, sometimes there are multiple user entries with the same username (this is an internal problem which we are aware of). As a workaround, I also added the second user with the name 'bekazhvania' to the project as well. Can you confirm this solves the problem?
![image](https://user-images.githubusercontent.com/6236455/167615844-7cf5f9a5-acc3-460b-be0a-453375e912d9.png)

I'm hoping to resolve the duplicate user problem soon.

**Comment by MaxKissgen** [comment]
The workaround works! We just tried it

**Comment by fxjordan** [comment]
Fix is finally deployed
